### ISSUE TITLE
ffmpeg not found when extracting mp3 from YouTube video

### ISSUE THREAD

**Issue by tansowny-tech** [degville/snap-yt-dlp#4]
When trying to extract an mp3 file from a YouTube video using the following command:

```
yt-dlp --embed-thumbnail --extract-audio --audio-format mp3 --audio-quality 0 'video-url'
```

The error that shows up is:

```
ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
````

The problem occurs on the **beta** and **edge** channels but does not occur on **candidate**. I didn't test **stable**.

**Comment by degville** [comment]
Thanks for reporting this, and for including the example..

We recently merged an update that uses an external content snap to provide ffmpeg, rather than include it in the snap. However, we've not yet got the snap connection in-place to make the connection automatically.

For now, I've decided to revert to including ffmpeg until I can look through the content snap (which I may now put in a different track). The new snap is now in edge/beta, and it should work as before.

**Comment by soumyaDghosh** [comment]
I got the problem, the ffmpeg content snap needs to be connected as of now. That needs an auto connection request in the forum. That's why I was making some hurry in the comments before.

eg: 

https://forum.snapcraft.io/t/autoconnect-request-to-content-snap-ffmpeg-2204-for-the-snaps-tube-converter-and-tagger/35811

**Comment by degville** [comment]
I'm going to close this as I've decided to keep bundling ffmpeg in the snap for now.
